import { Poppins } from 'next/font/google'
import './globals.css'
import AuthContext from './context/AuthContext'
import ToastContext from './context/ToastContext'

const poppins = Poppins({ subsets: ['latin'], weight: "400", display: "swap" })

export const metadata= {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthContext>
          <ToastContext/>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
